# Generated by Django 5.2.13 on 2026-04-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
