# Generated by Django 5.2.13 on 2026-04-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_api", "0002_invoice_amount_invoice_date_invoice_invoice_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceCorrection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("field_name", models.CharField(max_length=64)),
                ("original_value", models.TextField(blank=True, null=True)),
                ("corrected_value", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="invoice_api.invoice",
                    ),
                ),
            ],
        ),
    ]

