# Generated by Django 5.2.9 on 2026-04-18 07:54

from django.db import migrations, models
from decimal import Decimal, InvalidOperation
from datetime import datetime
import re


def _parse_amount(raw: str | None) -> str | None:
    if raw is None:
        return None
    s = str(raw).strip()
    if not s:
        return None
    m = re.search(r"[-+]?\d[\d,]*([.]\d+)?", s)
    if not m:
        return None
    token = m.group(0).replace(",", "")
    try:
        # Normalize to a plain decimal string
        return str(Decimal(token))
    except (InvalidOperation, ValueError):
        return None


_DATE_FORMATS: tuple[str, ...] = (
    "%Y-%m-%d",
    "%d-%m-%Y",
    "%d/%m/%Y",
    "%m/%d/%Y",
    "%d %b %Y",
    "%d %B %Y",
    "%b %d %Y",
    "%B %d %Y",
)


def _parse_date_iso(raw: str | None) -> str | None:
    if raw is None:
        return None
    s = str(raw).strip()
    if not s:
        return None
    s_norm = re.sub(r"\s+", " ", s)
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(s_norm, fmt).date().isoformat()
        except ValueError:
            continue
    m = re.search(r"(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})", s_norm)
    if m:
        d1, d2, y = m.group(1), m.group(2), m.group(3)
        if len(y) == 2:
            y = "20" + y
        for fmt in ("%d/%m/%Y", "%m/%d/%Y"):
            try:
                return datetime.strptime(f"{d1}/{d2}/{y}", fmt).date().isoformat()
            except ValueError:
                continue
    return None


def forward_copy_and_normalize(apps, schema_editor):
    Invoice = apps.get_model("invoice_api", "Invoice")
    for inv in Invoice.objects.all().only("id", "amount", "date", "amount_raw", "date_raw"):
        amount_old = getattr(inv, "amount", None)
        date_old = getattr(inv, "date", None)

        # Preserve original strings
        inv.amount_raw = amount_old
        inv.date_raw = date_old

        # Normalize for typed migration (store ISO/decimal strings; invalid -> None)
        inv.amount = _parse_amount(amount_old)
        inv.date = _parse_date_iso(date_old)
        inv.save(update_fields=["amount_raw", "date_raw", "amount", "date"])


def backward_noop(apps, schema_editor):
    # Intentionally no-op: raw fields keep the historical OCR/user values.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_api', '0003_invoicecorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(forward_copy_and_normalize, backward_noop),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
